#pragma once

// From glfw3.h
#define TULIP_MOUSE_BUTTON_1         0
#define TULIP_MOUSE_BUTTON_2         1
#define TULIP_MOUSE_BUTTON_3         2
#define TULIP_MOUSE_BUTTON_4         3
#define TULIP_MOUSE_BUTTON_5         4
#define TULIP_MOUSE_BUTTON_6         5
#define TULIP_MOUSE_BUTTON_7         6
#define TULIP_MOUSE_BUTTON_8         7
#define TULIP_MOUSE_BUTTON_LAST      TULIP_MOUSE_BUTTON_8
#define TULIP_MOUSE_BUTTON_LEFT      TULIP_MOUSE_BUTTON_1
#define TULIP_MOUSE_BUTTON_RIGHT     TULIP_MOUSE_BUTTON_2
#define TULIP_MOUSE_BUTTON_MIDDLE    TULIP_MOUSE_BUTTON_3